service: enginehub-pastebin

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128

plugins:
- serverless-nextjs-plugin
- serverless-offline

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**

custom:
  serverless-nextjs:
    customHandler: ./handler.js
    assetsBucketName: "paste-static.enginehub.org"
    routes:
      - src: api/paste
        path: paste
      - src: api/documents/[id]
        path: documents/{id}
        request:
          parameters:
            paths:
              id: true
      - src: _error
        path: "404"
