runtime: nodejs12
service: builds 
handlers:
  - url: /_next/static
    static_dir: build/static
  - url: /static
    static_dir: public/static
  - url: /.*
    script: auto
automatic_scaling:
  max_instances: 2
  max_idle_instances: 1
