name: Node CI

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Test and Deploy
      run: |
        npm install -g yarn serverless
        yarn
        yarn workspace builds type-check
        yarn workspace builds deploy 
      env:
        CI: true
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}